
site_name: EPCIS Mediation Gateway
site_description: A mediation gateway which translates information from NGSI based IoT platform to EPCIS based IoT platform
docs_dir: docs
site_dir: html
edit_uri: edit/master/docs/
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
repo_url: https://github.com/yalewkidane/FIWARE_EPCIS_Mediation_Gateway
repo_name: GitHub
site_url: https://fiware-epcis-gateway.readthedocs.io

pages:
    -  Home: index.md
    - 'Install' : 'install.md'
    - 'Usage' : 'usage.md'
    - 'Appendix' : 'appendix.md'

theme: readthedocs
extra_css: ["https://www.fiware.org/style/fiware_readthedocs.css", "https://www.fiware.org/style/fiware_readthedocs_iot.css"]
